package cli

import (
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// TestScaffoldCompatibility checks ADR-0016's scaffold compatibility promise
// (ADR-0054) and the v0.2 additive rule (roadmap decision D2): Full single-
// and multi-tenant apps generated by a released orb build and pass their
// tests against the library in this checkout, unchanged.
//
// Set ORB_COMPAT=1 to run it. By default it builds orb from the latest v1.*
// tag in this checkout and creates the apps with --local. ORB_COMPAT_FROM
// names another tag or commit, such as ORB_COMPAT_FROM=v0.1.0.
//
// With ORB_COMPAT_PUBLISHED=1 it checks what a user of that release has
// instead: it installs gorbital.dev/cli/cmd/orb@$ORB_COMPAT_FROM from the
// module proxy, creates the apps against the published library, and then
// points every library module at this checkout with go mod edit -replace.
//
// It needs the Go module cache or network, the tag or commit in this
// checkout unless ORB_COMPAT_PUBLISHED is set (git fetch --tags), and the
// Docker PostgreSQL and Mailpit for the apps' own tests.
func TestScaffoldCompatibility(t *testing.T) {
	if os.Getenv("ORB_COMPAT") == "" {
		t.Skip("set ORB_COMPAT=1 to run the scaffold compatibility check")
	}
	repo, err := filepath.Abs(repoRoot(t))
	if err != nil {
		t.Fatal(err)
	}
	published := os.Getenv("ORB_COMPAT_PUBLISHED") != ""
	tag := os.Getenv("ORB_COMPAT_FROM")
	if published && tag == "" {
		t.Fatal("ORB_COMPAT_PUBLISHED needs ORB_COMPAT_FROM=<released version>, such as v0.1.0")
	}
	if tag == "" {
		latest, err := gitOutput(t.Context(), repo, "tag", "--list", "v1.*", "--sort=-v:refname")
		if err != nil {
			t.Fatalf("git tag: %v", err)
		}
		if tag, _, _ = strings.Cut(latest, "\n"); tag == "" {
			t.Skip("no v1.* tag in this checkout yet, so no released scaffold carries the promise; run git fetch --tags, or set ORB_COMPAT_FROM=<tag or commit> to check an earlier one")
		}
	}

	work := t.TempDir()
	var orb string
	if published {
		t.Logf("scaffold of the published orb %s, library of this checkout", tag)
		orb = installPublishedOrb(t, work, tag)
	} else {
		t.Logf("scaffold of %s, library of this checkout", tag)
		orb = buildOrbAt(t, repo, work, tag)
	}

	var replaces []string
	if published {
		replaces = libraryReplaces(t, repo)
	}
	for _, tenancy := range []string{"single", "multi"} {
		t.Run("full-"+tenancy, func(t *testing.T) {
			dir := t.TempDir()
			name := "compat-" + tenancy
			args := []string{"new", name, "--preset", "full", "--tenancy", tenancy, "--no-git", "--skip-tidy", "--json"}
			if published {
				// The published library, as a user of the release gets it.
				args = append(args, "--no-input", "--no-start")
			} else {
				// Replace directives pointing at this checkout.
				args = append(args, "--local", repo)
			}
			create := exec.Command(orb, args...)
			create.Dir = dir
			if out, err := create.CombinedOutput(); err != nil {
				t.Fatalf("orb %s %s: %v\n%s", tag, strings.Join(args, " "), err, out)
			}
			app := filepath.Join(dir, name)
			steps := [][]string{{"mod", "tidy"}, {"build", "./..."}, {"vet", "./..."}, {"test", "./..."}}
			if published {
				steps = slices.Insert(steps, 0, append([]string{"mod", "edit"}, replaces...))
			}
			for _, args := range steps {
				cmd := exec.Command("go", args...)
				cmd.Dir = app
				if out, err := cmd.CombinedOutput(); err != nil {
					t.Fatalf("an app generated by orb %s fails go %s against this library: %v\n%s", tag, strings.Join(args, " "), err, out)
				}
				if published && args[0] == "mod" && args[1] == "tidy" {
					// The check is only worth something against this checkout.
					list := exec.Command("go", "list", "-m", "-f", "{{with .Replace}}{{.Path}}{{end}}", "gorbital.dev")
					list.Dir = app
					if out, err := list.Output(); err != nil || strings.TrimSpace(string(out)) != repo {
						t.Fatalf("gorbital.dev in the app isn't replaced by %s: %q, %v", repo, out, err)
					}
				}
			}
		})
	}
}

// buildOrbAt builds orb from the source of tag in a temporary worktree.
func buildOrbAt(t *testing.T, repo, work, tag string) string {
	t.Helper()
	if _, err := gitOutput(t.Context(), repo, "rev-parse", "--verify", "--quiet", tag+"^{commit}"); err != nil {
		t.Fatalf("%s isn't in this checkout (git fetch --tags)", tag)
	}
	old := filepath.Join(work, "orb-src")
	if out, err := exec.Command("git", "-C", repo, "worktree", "add", "--detach", "--quiet", old, tag).CombinedOutput(); err != nil {
		t.Fatalf("git worktree add: %v\n%s", err, out)
	}
	t.Cleanup(func() {
		if out, err := exec.Command("git", "-C", repo, "worktree", "remove", "--force", old).CombinedOutput(); err != nil {
			t.Logf("git worktree remove: %v\n%s", err, out)
		}
	})
	orb := filepath.Join(work, "orb-"+tag)
	// The command's directory is cli/cmd/orb, or cli/cmd/aps before the
	// rename to gorbital.
	commands, _ := filepath.Glob(filepath.Join(old, "cli", "cmd", "*"))
	if len(commands) != 1 {
		t.Fatalf("want one command in cli/cmd at %s, found %v", tag, commands)
	}
	build := exec.Command("go", "build", "-o", orb, ".")
	build.Dir = commands[0]
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build orb %s: %v\n%s", tag, err, out)
	}
	return orb
}

// installPublishedOrb installs orb at version from the module proxy.
func installPublishedOrb(t *testing.T, work, version string) string {
	t.Helper()
	bin := filepath.Join(work, "bin")
	install := exec.Command("go", "install", "gorbital.dev/cli/cmd/orb@"+version)
	install.Dir = work
	install.Env = append(os.Environ(), "GOBIN="+bin, "GOWORK=off", "GOFLAGS=")
	if out, err := install.CombinedOutput(); err != nil {
		t.Fatalf("go install gorbital.dev/cli/cmd/orb@%s: %v\n%s", version, err, out)
	}
	return filepath.Join(bin, "orb")
}

// libraryReplaces returns go mod edit arguments pointing every library
// module in the checkout (gorbital.dev and gorbital.dev/modules/...) at its
// directory.
func libraryReplaces(t *testing.T, repo string) []string {
	t.Helper()
	var args []string
	err := filepath.WalkDir(repo, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "node_modules", "testdata", "examples", "spikes", "internal", "cli":
				if path != repo {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if d.Name() != "go.mod" {
			return nil
		}
		goMod, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		module := modulePath(goMod)
		if module == "gorbital.dev" || strings.HasPrefix(module, "gorbital.dev/modules/") {
			args = append(args, "-replace="+module+"="+filepath.Dir(path))
		}
		return nil
	})
	if err != nil {
		t.Fatalf("find library modules: %v", err)
	}
	if len(args) < 2 {
		t.Fatalf("found only %v library modules in %s", args, repo)
	}
	return args
}
