package cli

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestScaffoldCompatibility checks ADR-0016's scaffold compatibility promise
// (ADR-0054): Full single- and multi-tenant apps generated by the orb of the
// latest v1.* tag build and pass their tests against the library in this
// checkout, unchanged. Set ORB_COMPAT=1 to run it, and ORB_COMPAT_FROM to
// check another tag, such as ORB_COMPAT_FROM=v0.5.0 (releases before v1.0
// were allowed to break). It needs the tag in this checkout (git fetch
// --tags), the Go module cache or network, and the Docker PostgreSQL and
// Mailpit for the apps' own tests.
func TestScaffoldCompatibility(t *testing.T) {
	if os.Getenv("ORB_COMPAT") == "" {
		t.Skip("set ORB_COMPAT=1 to run the scaffold compatibility check")
	}
	repo, err := filepath.Abs(repoRoot(t))
	if err != nil {
		t.Fatal(err)
	}
	tag := os.Getenv("ORB_COMPAT_FROM")
	if tag == "" {
		latest, err := gitOutput(t.Context(), repo, "tag", "--list", "v1.*", "--sort=-v:refname")
		if err != nil {
			t.Fatalf("git tag: %v", err)
		}
		if tag, _, _ = strings.Cut(latest, "\n"); tag == "" {
			t.Skip("no v1.* tag in this checkout yet, so no released scaffold carries the promise; run git fetch --tags, or set ORB_COMPAT_FROM=<tag> to check an earlier release")
		}
	}
	if _, err := gitOutput(t.Context(), repo, "rev-parse", "--verify", "--quiet", tag+"^{commit}"); err != nil {
		t.Fatalf("tag %s isn't in this checkout (git fetch --tags)", tag)
	}
	t.Logf("scaffold of %s, library of this checkout", tag)

	// Build orb as released at the tag.
	work := t.TempDir()
	old := filepath.Join(work, "orb-src")
	if out, err := exec.Command("git", "-C", repo, "worktree", "add", "--detach", "--quiet", old, tag).CombinedOutput(); err != nil {
		t.Fatalf("git worktree add: %v\n%s", err, out)
	}
	t.Cleanup(func() {
		if out, err := exec.Command("git", "-C", repo, "worktree", "remove", "--force", old).CombinedOutput(); err != nil {
			t.Logf("git worktree remove: %v\n%s", err, out)
		}
	})
	oldOrb := filepath.Join(work, "orb-"+tag)
	// The command's directory is cli/cmd/orb, or cli/cmd/aps before the
	// rename to gorbital.
	commands, _ := filepath.Glob(filepath.Join(old, "cli", "cmd", "*"))
	if len(commands) != 1 {
		t.Fatalf("want one command in cli/cmd at %s, found %v", tag, commands)
	}
	build := exec.Command("go", "build", "-o", oldOrb, ".")
	build.Dir = commands[0]
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build orb %s: %v\n%s", tag, err, out)
	}

	for _, tenancy := range []string{"single", "multi"} {
		t.Run("full-"+tenancy, func(t *testing.T) {
			dir := t.TempDir()
			name := "compat-" + tenancy
			// The old scaffold, with replace directives pointing at this
			// checkout: the library a go get would bring.
			create := exec.Command(oldOrb, "new", name, "--preset", "full", "--tenancy", tenancy, "--local", repo, "--no-git", "--skip-tidy", "--json")
			create.Dir = dir
			if out, err := create.CombinedOutput(); err != nil {
				t.Fatalf("orb %s new --preset full --tenancy %s: %v\n%s", tag, tenancy, err, out)
			}
			app := filepath.Join(dir, name)
			for _, args := range [][]string{{"mod", "tidy"}, {"build", "./..."}, {"vet", "./..."}, {"test", "./..."}} {
				cmd := exec.Command("go", args...)
				cmd.Dir = app
				if out, err := cmd.CombinedOutput(); err != nil {
					t.Fatalf("an app generated by orb %s fails go %s against this library: %v\n%s", tag, strings.Join(args, " "), err, out)
				}
			}
		})
	}
}
