// Package ipfilter refuses requests by client address with 403
// ip_not_allowed (ADR-0085):
//
//	allow, err := ipfilter.ParsePrefixes(os.Getenv("OFFICE_RANGES"))
//	onlyOffice, err := ipfilter.New(allow, nil)
//	handler := httpx.Chain(mux, httpx.TrustedProxies(proxies), onlyOffice)
//
// gorbital.dev/gorbital/opshttp puts every /ops/ route behind it when
// OPS_ALLOWED_IPS is set.
//
// It is a package of its own, not part of httpx, because apps generated by
// orb v0.1 record every problem code of the gorbital.dev packages they link
// in api/surface.json: a new code in httpx would fail their tests
// (docs/guides/stability.md).
//
// Stability: experimental until v0.2.0 (ADR-0015, ADR-0081).
package ipfilter

import (
	"errors"
	"fmt"
	"net/http"
	"net/netip"
	"strings"

	"gorbital.dev/httpx"
)

// ErrDenyAll reports a deny range covering every IPv4 or IPv6 address,
// which would refuse every request of that family.
var ErrDenyAll = errors.New("ipfilter: a deny range can't cover every address; list the allowed ranges instead")

// ParsePrefixes reads a comma-separated list of CIDR ranges or single
// addresses, such as "10.0.0.0/8, 2001:db8::/32, 192.0.2.10", for
// [New]. Ranges are masked ("10.0.0.5/8" is 10.0.0.0/8), and IPv4
// addresses written in IPv6 form ("::ffff:10.0.0.5") become IPv4, as client
// addresses are compared. An empty list returns nil.
func ParsePrefixes(list string) ([]netip.Prefix, error) {
	var out []netip.Prefix
	for item := range strings.SplitSeq(list, ",") {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		p, err := netip.ParsePrefix(item)
		if err != nil {
			addr, addrErr := netip.ParseAddr(item)
			if addrErr != nil || addr.Zone() != "" {
				return nil, fmt.Errorf("ipfilter: %q is not a CIDR range or IP address", item)
			}
			p = netip.PrefixFrom(addr, addr.BitLen())
		}
		p, err = canonicalPrefix(p)
		if err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, nil
}

// canonicalPrefix masks p and turns an IPv4-mapped IPv6 range into its IPv4
// range. A mapped range shorter than /96 mixes families and is refused.
func canonicalPrefix(p netip.Prefix) (netip.Prefix, error) {
	if !p.IsValid() {
		return netip.Prefix{}, fmt.Errorf("ipfilter: invalid IP range %v", p)
	}
	if p.Addr().Is4In6() {
		if p.Bits() < 96 {
			return netip.Prefix{}, fmt.Errorf("ipfilter: IP range %v mixes IPv4-mapped and IPv6 addresses; write the IPv4 range", p)
		}
		p = netip.PrefixFrom(p.Addr().Unmap(), p.Bits()-96)
	}
	return p.Masked(), nil
}

// New returns middleware that refuses requests by client address with a
// 403 problem, code "ip_not_allowed". The address is the request's
// RemoteAddr, so behind a proxy install httpx.TrustedProxies first. A request
// is refused when its address is in a deny range, or when allow isn't empty
// and its address is in no allow range: deny wins, and an empty allow list
// allows every address not denied. A RemoteAddr that isn't an IP address is
// refused. IPv4-mapped IPv6 addresses are compared as IPv4, and IPv6 zones
// are ignored.
//
// It returns an error for an invalid range, a deny range covering every
// address of a family ([ErrDenyAll]; list allowed ranges instead), or an
// allow range entirely inside a deny range, which could never match. With
// both lists empty the middleware changes nothing.
func New(allow, deny []netip.Prefix) (httpx.Middleware, error) {
	allow, err := canonicalPrefixes(allow)
	if err != nil {
		return nil, err
	}
	deny, err = canonicalPrefixes(deny)
	if err != nil {
		return nil, err
	}
	for _, d := range deny {
		if d.Bits() == 0 {
			return nil, fmt.Errorf("%w: %v", ErrDenyAll, d)
		}
		for _, a := range allow {
			if d.Bits() <= a.Bits() && d.Contains(a.Addr()) {
				return nil, fmt.Errorf("ipfilter: allow range %v is inside deny range %v and would never match", a, d)
			}
		}
	}
	return func(next http.Handler) http.Handler {
		if len(allow) == 0 && len(deny) == 0 {
			return next
		}
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			addr, ok := remoteAddr(r.RemoteAddr)
			addr = addr.WithZone("") // ranges have no zones
			if !ok || contains(deny, addr) || len(allow) > 0 && !contains(allow, addr) {
				httpx.WriteProblem(w, r, httpx.NewProblem(http.StatusForbidden, "ip_not_allowed", "requests from this network address are not allowed"))
				return
			}
			next.ServeHTTP(w, r)
		})
	}, nil
}

func canonicalPrefixes(in []netip.Prefix) ([]netip.Prefix, error) {
	if len(in) == 0 {
		return nil, nil
	}
	out := make([]netip.Prefix, len(in))
	for i, p := range in {
		c, err := canonicalPrefix(p)
		if err != nil {
			return nil, err
		}
		out[i] = c
	}
	return out, nil
}

// remoteAddr parses a request's RemoteAddr, with or without a port, as
// httpx.TrustedProxies does, unmapping IPv4-mapped addresses.
func remoteAddr(s string) (netip.Addr, bool) {
	if ap, err := netip.ParseAddrPort(s); err == nil {
		return ap.Addr().Unmap(), true
	}
	addr, err := netip.ParseAddr(s)
	return addr.Unmap(), err == nil
}

// contains reports whether a range of ranges contains addr.
func contains(ranges []netip.Prefix, addr netip.Addr) bool {
	for _, p := range ranges {
		if p.Contains(addr) {
			return true
		}
	}
	return false
}
