// Package auth provides the building blocks of email and password
// authentication: argon2id password hashing, session tokens and one-time
// codes stored only as hashes, email normalisation, session cookies, the
// request middleware, a permission catalog and plain authentication emails
// (ADR-0024, ADR-0038).
//
// Apps own their authentication flows, tables and SQL in
// internal/modules/auth (generated by orb new): its use cases call these
// helpers for the security-sensitive steps, so fixes to them arrive with
// go get, while every flow stays readable and editable in the app.
//
// Stability: pre-1.0 (ADR-0015).
package auth

import "time"

// Defaults and policy constants shared by generated apps.
const (
	DefaultSessionIdleTTL          = 14 * 24 * time.Hour
	DefaultSessionAbsoluteTTL      = 90 * 24 * time.Hour
	DefaultVerificationCodeTTL     = 15 * time.Minute
	DefaultResetCodeTTL            = 30 * time.Minute
	DefaultDeletedAccountRetention = 30 * 24 * time.Hour

	// DefaultLoginAttempts per email address within DefaultLoginWindow.
	DefaultLoginAttempts = 10
	DefaultLoginWindow   = 15 * time.Minute

	MinPasswordLength = 12
	MaxPasswordLength = 128

	// CodeMaxAttempts is how many guesses one code allows.
	CodeMaxAttempts = 5
	// CodeResendInterval is the shortest time between two codes of the same
	// purpose for one account.
	CodeResendInterval = time.Minute
	// SessionTouchInterval is the shortest time between two last-seen updates
	// of a session, so busy clients don't write on every request.
	SessionTouchInterval = time.Minute
	// EndedSessionRetention is how long ended sessions stay for
	// investigations before cleanup removes them.
	EndedSessionRetention = 7 * 24 * time.Hour
	// CodeRetention is how long codes stay before cleanup removes them.
	CodeRetention = 24 * time.Hour

	DefaultCookieName = "__Host-session"

	// MFAChallengeTTL is how long a sign-in waits for its second factor.
	MFAChallengeTTL = 5 * time.Minute
	// MFAChallengeMaxAttempts is how many wrong second factors one sign-in
	// allows.
	MFAChallengeMaxAttempts = 5
)

// Limits bounds a duration. Apps read durations from runtime settings and
// clamp them, so a setting can't weaken security beyond the limits.
type Limits struct {
	Min, Max time.Duration
}

// Clamp returns d within the limits.
func (l Limits) Clamp(d time.Duration) time.Duration {
	return min(max(d, l.Min), l.Max)
}

// Hard limits for authentication durations.
var (
	SessionIdleLimits      = Limits{Min: 5 * time.Minute, Max: 90 * 24 * time.Hour}
	SessionAbsoluteLimits  = Limits{Min: time.Hour, Max: 365 * 24 * time.Hour}
	VerificationCodeLimits = Limits{Min: time.Minute, Max: time.Hour}
	ResetCodeLimits        = Limits{Min: time.Minute, Max: 2 * time.Hour}
	DeletedRetentionLimits = Limits{Min: 0, Max: 365 * 24 * time.Hour}
)
