// Code generated by orb gen modules. DO NOT EDIT.

// Package modules lists the app's modules for main.go. Each directory
// below declares one, with func Module() gorbital.Module; orb dev and
// go generate rewrite this file when one is added or removed.
package modules

//go:generate orb gen modules

import (
	"gorbital.dev/gorbital"

	"example.com/mobile-backend/internal/modules/trips"
)

// All returns every module of the app, sorted by directory name.
func All() []gorbital.Module {
	return []gorbital.Module{
		trips.Module(),
	}
}
