# Guide for AI coding assistants

This is a Go API generated by apistock. Read [ARCHITECTURE.md](ARCHITECTURE.md) before changing code.

## Commands

| Purpose | Command |
|---|---|
| Test (must pass before finishing) | `go test ./...` |
| Vet | `go vet ./...` |
| Run locally | `go run ./cmd/api` (or `aps dev`) |
| See traces, metrics and logs | `aps dev --observability` (Grafana on http://127.0.0.1:3000; needs Docker) |
| Update the API contract (openapi.json, Postman collection, llms.txt) after changing endpoints | `go run ./cmd/api openapi --dir api` |

## Where code goes

| Change | Location |
|---|---|
| Business rule or domain error | `internal/modules/<module>/domain/` |
| Application logic | `internal/modules/<module>/usecase/` |
| Interface for storage or external services | `internal/modules/<module>/usecase/ports.go` |
| HTTP endpoint | `internal/modules/<module>/delivery/` (`huma.Register`) |
| Domain error → HTTP status and error code | `internal/app/module_<module>.go` |
| New setting | `internal/app/config.go` and `.env.example` |
| New module | `internal/modules/<module>/`, `internal/app/module_<module>.go`, one line in `internal/app/modules.go` |

## Rules

- Keep `domain/` free of third-party imports and struct tags.
- Never read environment variables outside `internal/app`.
- Never import one module from another.
- Return domain errors from handlers; don't build HTTP errors in use cases.
- Request body structs start with ``_ struct{} `json:"-" additionalProperties:"true"` `` so unknown fields are ignored.
- Error codes are public API: add new ones, never rename existing ones.
- Never log secrets, tokens, passwords or email addresses; log IDs.
- Keep `//aps:anchor` comments; apistock uses them to add modules.
